#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".



test -n "$(grep -E '^(Fix|Feat|Docs|Style|Refactor|Test|Chore)\s#\d+:.*$' ${1})" || {
        echo >&2 "ERROR: Your commit message is not formatted correctly"
        exit 1
}

